# Generated by Django 3.0.7 on 2020-07-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='merch',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
