# Generated by Django 3.0.7 on 2020-07-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0002_auto_20200728_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='large_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='medium_image',
        ),
    ]
