# Generated by Django 3.0.7 on 2020-07-30 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0005_auto_20200730_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='merch',
            name='published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
