# Generated by Django 3.0.7 on 2020-07-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0006_auto_20200730_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('anime', 'Anime'), ('series', 'Series')], default='movie', max_length=55),
        ),
        migrations.AddField(
            model_name='merch',
            name='collection_type',
            field=models.CharField(blank=True, choices=[('poster', 'Poster'), ('clothes', 'Clothes'), ('mug', 'Mug')], max_length=20, null=True),
        ),
    ]
