# Generated by Django 3.0.7 on 2020-07-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0009_auto_20200731_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_type',
            field=models.CharField(blank=True, choices=[('movie', 'Movie'), ('anime', 'Anime'), ('series', 'Series')], max_length=55, null=True),
        ),
    ]
