# Generated by Django 3.0.7 on 2020-07-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0010_auto_20200731_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_type',
        ),
    ]
