# Generated by Django 3.0.7 on 2020-07-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0012_remove_merch_collection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
