# Generated by Django 3.0.7 on 2020-07-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0014_auto_20200731_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='short_description',
        ),
    ]
