# Generated by Django 3.0.7 on 2020-07-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0015_remove_collection_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='merch',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
