# Generated by Django 3.0.7 on 2020-07-31 15:22

from django.db import migrations, models
import reusable.models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0016_auto_20200731_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=reusable.models.image_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=reusable.models.image_path),
        ),
        migrations.AlterField(
            model_name='merch',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=reusable.models.image_path),
        ),
    ]
