# Generated by Django 3.0.7 on 2020-07-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0019_auto_20200731_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='reusable/<function image_path at 0x0486F6E8>'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='reusable/<function image_path at 0x0486F6E8>'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='reusable/<function image_path at 0x0486F6E8>'),
        ),
    ]
