# Generated by Django 3.0.7 on 2020-07-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0020_auto_20200731_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='<function image_path at 0x045AF6E8>'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='<function image_path at 0x045AF6E8>'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='<function image_path at 0x045AF6E8>'),
        ),
    ]
