# Generated by Django 3.0.7 on 2020-08-04 16:37

from django.db import migrations, models
import reusable.models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0022_auto_20200731_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=reusable.models.image_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=reusable.models.image_path),
        ),
        migrations.AlterField(
            model_name='merch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=reusable.models.image_path),
        ),
    ]
