# Generated by Django 3.0.7 on 2020-06-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200623_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('born', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='directors/')),
            ],
        ),
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
        migrations.AddField(
            model_name='actor',
            name='born',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
