# Generated by Django 3.0.7 on 2020-06-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200628_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='genre',
            name='movie',
            field=models.ManyToManyField(to='main.Movie'),
        ),
        migrations.AddField(
            model_name='quality',
            name='quality_1080_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='quality_1080_bluray',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='quality_720_bluray',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='quality_720_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
