# Generated by Django 3.0.7 on 2020-07-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200702_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='quality',
        ),
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.ManyToManyField(to='main.Quality'),
        ),
    ]
