# Generated by Django 3.0.7 on 2020-07-02 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200702_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='quality',
        ),
        migrations.AddField(
            model_name='quality',
            name='movie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Movie'),
        ),
    ]
