# Generated by Django 3.0.7 on 2020-07-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200702_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='qualities',
        ),
        migrations.AddField(
            model_name='movie',
            name='qualities',
            field=models.ManyToManyField(blank=True, null=True, to='main.Quality'),
        ),
    ]
