# Generated by Django 3.0.7 on 2020-07-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
    ]
