# Generated by Django 3.0.7 on 2020-07-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20200711_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactername',
            name='cast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='main.Cast'),
        ),
    ]
