# Generated by Django 3.0.7 on 2020-07-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_movie_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
    ]
