# Generated by Django 3.0.7 on 2020-07-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_movie_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrents',
            name='peers',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='torrents',
            name='quality_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='torrents',
            name='seeds',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
