# Generated by Django 3.0.7 on 2020-07-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_reviews_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
