# Generated by Django 3.0.7 on 2020-07-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0001_initial'),
        ('main', '0075_auto_20200725_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='collection',
            field=models.ManyToManyField(to='reusable.Collection'),
        ),
        migrations.AddField(
            model_name='movie',
            name='merch',
            field=models.ManyToManyField(to='reusable.Merch'),
        ),
    ]
