# Generated by Django 3.0.7 on 2020-07-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_torrents_tor_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrents',
            name='tor_hash',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
