# Generated by Django 3.0.7 on 2020-07-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0004_company'),
        ('main', '0078_auto_20200730_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reusable.Company'),
        ),
    ]
