# Generated by Django 3.0.7 on 2020-07-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0007_auto_20200730_2200'),
        ('main', '0079_movie_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='collection',
            field=models.ManyToManyField(blank=True, null=True, to='reusable.Collection'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='merch',
            field=models.ManyToManyField(blank=True, null=True, to='reusable.Merch'),
        ),
    ]
