# Generated by Django 3.0.7 on 2020-07-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0007_auto_20200730_2200'),
        ('main', '0081_auto_20200731_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='merch',
            field=models.ManyToManyField(blank=True, to='reusable.Merch'),
        ),
    ]
