# Generated by Django 3.0.7 on 2020-07-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0009_auto_20200731_1130'),
        ('main', '0083_auto_20200731_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='collection',
            field=models.ManyToManyField(blank=True, to='reusable.Collection'),
        ),
    ]
