# Generated by Django 3.0.7 on 2020-12-09 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('main', '0088_auto_20200804_1801'), ('main', '0089_auto_20201202_1610')]

    dependencies = [
        ('reusable', '0024_auto_20200810_1217'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0087_movie_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='users_like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collection_movies', to='reusable.Collection'),
        ),
    ]
