# Generated by Django 3.0.7 on 2020-08-04 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0087_movie_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='users_like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
