# Generated by Django 3.0.7 on 2020-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='torrent',
        ),
        migrations.AddField(
            model_name='torrent',
            name='genre',
            field=models.CharField(default='Add a genre', max_length=100),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='torrent-images'),
        ),
    ]
