# Generated by Django 3.0.7 on 2020-06-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200623_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='year',
            field=models.CharField(default=2051, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torrent',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Anime', 'Anime')], max_length=25),
        ),
    ]
