# Generated by Django 3.0.7 on 2020-06-23 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_crew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(upload_to='actors/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie-images')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('actors', models.ManyToManyField(related_name='film_actor', to='main.Actor')),
                ('directors', models.ManyToManyField(related_name='film_director', to='main.Actor')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=5000)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movie')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Reviews')),
            ],
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='author',
        ),
        migrations.RemoveField(
            model_name='file',
            name='torrent',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='torrent',
        ),
        migrations.RemoveField(
            model_name='subtitles',
            name='torrent',
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(default='Hey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='test-slug', max_length=125, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtitles',
            name='language',
            field=models.CharField(max_length=55),
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
        migrations.DeleteModel(
            name='Torrent',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='main.Genre'),
        ),
        migrations.AddField(
            model_name='file',
            name='movie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.Movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quality',
            name='movie',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='main.Movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='main.Movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtitles',
            name='movie',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='main.Movie'),
            preserve_default=False,
        ),
    ]
