# Generated by Django 3.0.7 on 2020-06-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200624_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.ManyToManyField(to='main.Quality'),
        ),
    ]
