# Generated by Django 3.0.7 on 2020-06-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200624_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality',
            name='quality',
        ),
        migrations.AddField(
            model_name='quality',
            name='quality_1080',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='quality',
            name='quality_360',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='quality',
            name='quality_480',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='quality',
            name='quality_720',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
