# Generated by Django 3.0.7 on 2020-06-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200624_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='movie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Movie'),
        ),
    ]
