# Generated by Django 3.0.7 on 2020-06-25 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200625_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Movie'),
        ),
    ]
