# Generated by Django 3.0.7 on 2020-06-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200625_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitles',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('de', 'German')], default='en', max_length=55),
        ),
    ]
