# Generated by Django 3.0.7 on 2020-06-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200625_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quality',
            old_name='quality_1080',
            new_name='quality_1080_bluray',
        ),
        migrations.RenameField(
            model_name='quality',
            old_name='quality_360',
            new_name='quality_720_bluray',
        ),
        migrations.RenameField(
            model_name='quality',
            old_name='quality_480',
            new_name='quality_720_web',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='quality_720',
        ),
    ]
