# Generated by Django 3.0.7 on 2020-06-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200630_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='background_image_original',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='large_cover_image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='large_screenshot_image1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='large_screenshot_image2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='large_screenshot_image3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='medium_cover_image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='medium_screenshot_image1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='medium_screenshot_image2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='medium_screenshot_image3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='small_cover_image',
        ),
    ]
