# Generated by Django 3.0.7 on 2020-07-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200702_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torrents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Torrents',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='qualities',
        ),
        migrations.DeleteModel(
            name='Quality',
        ),
        migrations.AddField(
            model_name='torrents',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Movie'),
        ),
    ]
