# Generated by Django 3.0.7 on 2020-07-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200702_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrents',
            name='size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
