# Generated by Django 3.0.7 on 2020-07-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20200711_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='url_small_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
