# Generated by Django 3.0.7 on 2020-07-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20200711_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactername',
            name='cast',
        ),
        migrations.AddField(
            model_name='charactername',
            name='cast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Cast'),
        ),
    ]
