# Generated by Django 3.0.7 on 2020-07-22 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20200721_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
