# Generated by Django 3.0.7 on 2020-07-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_movie_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='download_count',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='like_count',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='mpa_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
