# Generated by Django 3.0.7 on 2020-07-25 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20200725_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
